M48
; DRILL file {KiCad (6.0.7)} date Tue Nov  1 17:15:22 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-01T17:15:22-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0902
%
G90
G05
T1
X2.9384Y-1.4746
X2.9384Y-2.5364
X3.8183Y-2.0053
T0
M30
